### ISSUE TITLE
Add text input for the parameters for the APR interactive converter. 

### ISSUE THREAD

**Issue by cheesema** [AdaptiveParticles/PyLibAPR#23]
Currently the parameters via the sliders are restricted to integer values, and the user cannot directly input a value. 

This could be resolve with either a direct input box, or making the sliders have fixed number of increments over the min/ max range allowing non-integer values. (The second will require a bit more of a refactor or re-write as far as I can tell because the sliders we use seem to work only using int).

**Comment by joeljonsson** [comment]
PR #25 extends the sliders to allow decimal steps. Finding an exact value using the sliders can still be a bit tricky (or impossible if the range is large and the step is small), but it can be done by setting the maximum to the value you want.

Do you think this is sufficient, or do we still want to add boxes for direct input?
