### ISSUE TITLE
Can't seem to get the reading IO for named channels and time-steps

### ISSUE THREAD

**Issue by cheesema** [AdaptiveParticles/PyLibAPR#49]
Results in a cannot be found, even through the writing seems to be putting it in the correct place. Will see if this is an issue on the C++ side.

**Comment by joeljonsson** [comment]
Do you have a reproducible example of this? It seems to be working for me. Although the current API is mainly developed with a single channel and time step in mind. It could be expanded to simplify handling of multi channel/time data in a single file.

**Comment by cheesema** [comment]
This was an issue on the C++ side to do with the write tree flag as mentioned in LibAPR, def needs to be removed and automated.
